# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simpleTest <- function(t, i, j, valuesCumsum, costRecord) {
    .Call(`_DUSTpartitioning_simpleTest`, t, i, j, valuesCumsum, costRecord)
}

DUST <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_DUST`, data, penalty)
}

simpleTestFlist <- function(t, i, pointerIt, valuesCumsum, costRecord) {
    .Call(`_DUSTpartitioning_simpleTestFlist`, t, i, pointerIt, valuesCumsum, costRecord)
}

DUSTflist <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_DUSTflist`, data, penalty)
}

simpleTestFlistP <- function(t, i, pointerIt, valuesCumsum, costRecord) {
    .Call(`_DUSTpartitioning_simpleTestFlistP`, t, i, pointerIt, valuesCumsum, costRecord)
}

DUSTflistp <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_DUSTflistp`, data, penalty)
}

simpleTestReverse <- function(t, i, j, valuesCumsum, costRecord) {
    .Call(`_DUSTpartitioning_simpleTestReverse`, t, i, j, valuesCumsum, costRecord)
}

DUSTreverse <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_DUSTreverse`, data, penalty)
}

simpleTestVector <- function(t, i, j, valuesCumsum, costRecord) {
    .Call(`_DUSTpartitioning_simpleTestVector`, t, i, j, valuesCumsum, costRecord)
}

DUSTvector <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_DUSTvector`, data, penalty)
}

logging <- function(txt) {
    invisible(.Call(`_DUSTpartitioning_logging`, txt))
}

resetLogging <- function(path) {
    invisible(.Call(`_DUSTpartitioning_resetLogging`, path))
}

rcpp_hello_world <- function() {
    .Call(`_DUSTpartitioning_rcpp_hello_world`)
}

PELTcpp <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_PELTcpp`, data, penalty)
}

