# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DUSTclass <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_DUSTclass`, data, penalty)
}

OP <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_OP`, data, penalty)
}

PELT <- function(data, penalty = 0) {
    .Call(`_DUSTpartitioning_PELT`, data, penalty)
}

simpleTest <- function(t, i, j, valuesCumsum, costRecord) {
    .Call(`_DUSTpartitioning_simpleTest`, t, i, j, valuesCumsum, costRecord)
}

explo <- function() {
    .Call(`_DUSTpartitioning_explo`)
}

generate_runif1 <- function(n) {
    invisible(.Call(`_DUSTpartitioning_generate_runif1`, n))
}

generate_runif2 <- function(n) {
    invisible(.Call(`_DUSTpartitioning_generate_runif2`, n))
}

logging <- function(txt) {
    invisible(.Call(`_DUSTpartitioning_logging`, txt))
}

resetLogging <- function(path) {
    invisible(.Call(`_DUSTpartitioning_resetLogging`, path))
}

